// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYmEKfmf2os6wggDNJKGD_1SDNm40Sh04',
    appId: '1:905393048791:web:1144b78615caf0fe517492',
    messagingSenderId: '905393048791',
    projectId: 'uper-app-4df8c',
    authDomain: 'uper-app-4df8c.firebaseapp.com',
    storageBucket: 'uper-app-4df8c.appspot.com',
    measurementId: 'G-D2FR1SHJZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmL-3SI0dtM38HDtIHxZwias5S-SuOS4A',
    appId: '1:905393048791:android:7e4a61d2b2c7d5d3517492',
    messagingSenderId: '905393048791',
    projectId: 'uper-app-4df8c',
    storageBucket: 'uper-app-4df8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpiw25XJq8BpoBJjhzGCzTh8HS8ReS1o',
    appId: '1:905393048791:ios:a76ff5b13218b4ab517492',
    messagingSenderId: '905393048791',
    projectId: 'uper-app-4df8c',
    storageBucket: 'uper-app-4df8c.appspot.com',
    iosBundleId: 'com.example.goCar',
  );
}
